const {chromium}=await import(process.env.PLAYWRIGHT_MODULE || 'playwright');
import assert from 'node:assert/strict';
const browser=await chromium.launch({executablePath:process.env.CHROME_EXECUTABLE || '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true});try{const page=await browser.newPage({viewport:{width:1360,height:1000}}),errors=[];page.on('pageerror',e=>errors.push(e.message));let signed=false,configured=true,accounts=[],connectBody,mutations=[];
await page.route('https://accounts.google.com/gsi/client',r=>r.fulfill({contentType:'text/javascript',body:`window.google={accounts:{id:{initialize(o){window.login=o.callback},renderButton(el){let b=document.createElement('button');b.textContent='Test Google sign in';b.onclick=()=>login({credential:'test'});el.append(b)},disableAutoSelect(){}}}};`}));await page.route('**/api/graph?source=obsidian',r=>r.fulfill({json:{account:'owner@example.com',graph:null}}));await page.route('**/api/config',r=>r.fulfill({json:{googleClientId:'test'}}));
await page.route('**/api/session',r=>{signed=r.request().method()!=='DELETE';return r.fulfill({json:{ok:true}});});
await page.route('**/api/accounts',r=>r.fulfill({status:signed?200:401,json:signed?{account:'owner@example.com',configured,accounts}:{error:'missing_token'}}));
await page.route('**/api/accounts/connect',r=>{connectBody=r.request().postDataJSON();return r.fulfill({json:{url:(process.env.PEOPLE_TEST_ORIGIN||'http://127.0.0.1:4183')+'/accounts.html?connection=connected'}});});
await page.route('**/api/accounts/sync',r=>{mutations.push(r.request().postDataJSON());return r.fulfill({json:{ok:true}});});
await page.route('**/api/accounts/disconnect',r=>{accounts=accounts.filter(a=>a.email!==r.request().postDataJSON().email);return r.fulfill({json:{ok:true}});});
await page.goto((process.env.PEOPLE_TEST_ORIGIN||'http://127.0.0.1:4183')+'/accounts.html');await page.getByRole('button',{name:'Test Google sign in'}).click();await page.locator('#accounts-area').waitFor({state:'visible'});await page.locator('#import-options summary').click();await page.getByLabel('Message history').selectOption('all');accounts=[{email:'work@example.com',status:'syncing',processed:25,lastSync:0,range:'all'}];await page.getByRole('button',{name:'Add Gmail inbox'}).click();await page.getByRole('heading',{name:'work@example.com'}).waitFor();assert.equal(connectBody.range,'all');assert.ok(await page.getByRole('button',{name:'Sync now',exact:true}).isDisabled());assert.match(await page.locator('#notice').innerText(),/first import/);
accounts=[{email:'work@example.com',status:'connected',processed:250,lastSync:Date.now(),range:'all'},{email:'personal@example.com',status:'reconnect',processed:0,lastSync:0,range:'recent',error:'reconnect_required'}];await page.reload();await page.getByRole('button',{name:'Reconnect',exact:true}).waitFor();await page.getByRole('button',{name:'Sync now',exact:true}).click();assert.equal(mutations[0].email,'work@example.com');assert.equal(mutations[0].range,undefined);await page.locator('#account-list .inbox').first().getByText('Manage inbox',{exact:true}).click();await page.getByRole('button',{name:'Import all history'}).click();assert.equal(mutations[1].range,'all');await page.screenshot({path:'/tmp/people-accounts.png',fullPage:true});page.on('dialog',d=>d.accept());await page.locator('#account-list .inbox').first().getByRole('button',{name:'Disconnect',exact:true}).click();await page.getByRole('heading',{name:'work@example.com'}).waitFor({state:'hidden'});
await page.setViewportSize({width:390,height:844});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:'/tmp/people-accounts-mobile.png',fullPage:true});await page.getByRole('button',{name:'Sign out',exact:true}).click();await page.getByRole('button',{name:'Test Google sign in'}).waitFor();assert.ok(await page.locator('#accounts-area').isHidden());configured=false;await page.getByRole('button',{name:'Test Google sign in'}).click();await page.locator('#accounts-area').waitFor({state:'visible'});assert.ok(await page.getByRole('button',{name:'Add Gmail inbox'}).isDisabled());assert.deepEqual(errors,[]);console.log('PASS: People sign-in, no-token inbox connect, history choice, background progress, sync/retry/reconnect UI, disconnect, mobile, logout, configuration gate.');}finally{await browser.close();}
