import {test} from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync} from 'node:fs';
import {deviceRoute,authenticateDevice} from '../src/cli-auth';
function fixture(){const sql=new DatabaseSync(':memory:');sql.exec(readFileSync('migrations/20260922_cli_devices.sql','utf8'));sql.exec(readFileSync('migrations/20260922_cli_devices.sql','utf8'));const db:any={prepare(q:string){let args:any[]=[];return {bind(...v:any[]){args=v;return this;},async first(){return sql.prepare(q).get(...args)??null;},async all(){return {results:sql.prepare(q).all(...args)};},async run(){return {meta:sql.prepare(q).run(...args)};}};},async batch(items:any[]){sql.exec('BEGIN');try{const r=[];for(const item of items)r.push(await item.run());sql.exec('COMMIT');return r;}catch(e){sql.exec('ROLLBACK');throw e;}}};return {env:{DB:db,TOKEN_SECRET:'secret'} as any,sql};}
const req=(path:string,body:any={},token?:string)=>new Request('https://people.test/api/cli/'+path,{method:'POST',headers:{origin:'https://people.test','content-type':'application/json','cf-connecting-ip':'127.0.0.1',...(token?{authorization:'Bearer '+token}:{})},body:JSON.stringify(body)});
test('device approval binds owner and token is one-use, hashed, revocable and scoped',async()=>{const {env,sql}=fixture();const start=await (await deviceRoute(req('device/start',{deviceName:'My Mac'}),env,null)).json() as any;assert.equal(start.interval,5);assert.ok(!start.verificationUri.includes(start.pollSecret));assert.equal((await deviceRoute(req('device/approve',{userCode:start.userCode}),env,null)).status,401);assert.equal((await deviceRoute(req('device/approve',{userCode:start.userCode}),env,'owner@test')).status,200);assert.equal((await deviceRoute(req('device/approve',{userCode:start.userCode}),env,'other@test')).status,400);const result=await (await deviceRoute(req('device/poll',start),env,null)).json() as any;assert.ok(result.token.startsWith('pgd1_'));assert.equal(result.owner,'owner@test');assert.equal(sql.prepare('select token_hash from cli_devices').get()?.token_hash===result.token,false);const auth=await authenticateDevice(req('v1/query',{},result.token),env);assert.equal(auth?.owner,'owner@test');assert.equal((await deviceRoute(req('device/poll',start),env,null)).status,400);assert.equal((await deviceRoute(req('devices/revoke',{id:auth!.deviceId}),env,'other@test')).status,404);await deviceRoute(req('logout',{},result.token),env,null);assert.equal(await authenticateDevice(req('v1/query',{},result.token),env),null);});
test('device exchange rejects foreign origins, expired challenges, bad secrets, rapid polling and excess starts',async()=>{const {env,sql}=fixture();const start=await (await deviceRoute(req('device/start',{deviceName:'Mac'}),env,null)).json() as any;const foreign=req('device/approve',{userCode:start.userCode});foreign.headers.set('origin','https://evil.test');assert.equal((await deviceRoute(foreign,env,'owner@test')).status,403);assert.equal((await deviceRoute(req('device/poll',{...start,pollSecret:'wrong'}),env,null)).status,400);assert.equal((await deviceRoute(req('device/poll',start),env,null)).status,202);assert.equal((await deviceRoute(req('device/poll',start),env,null)).status,429);sql.prepare('UPDATE cli_challenges SET expires_at=0').run();assert.equal((await deviceRoute(req('device/approve',{userCode:start.userCode}),env,'owner@test')).status,400);for(let i=0;i<9;i++)await deviceRoute(req('device/start',{deviceName:'Mac'}),env,null);assert.equal((await deviceRoute(req('device/start',{deviceName:'Mac'}),env,null)).status,429);});
