const {chromium}=await import(process.env.PLAYWRIGHT_MODULE||'playwright');
import assert from 'node:assert/strict';
const browser=await chromium.launch({headless:true,executablePath:process.env.CHROME_EXECUTABLE||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'});
try{
 const page=await browser.newPage({viewport:{width:1200,height:900}}),errors=[];page.on('pageerror',e=>errors.push(e.message));const base=process.env.PEOPLE_TEST_ORIGIN||'http://127.0.0.1:4183';
 await page.route('**/district-harness',r=>r.fulfill({contentType:'text/html',body:'<div id="host" style="width:950px;height:650px"></div>'}));await page.goto(base+'/district-harness');
 const stats=await page.evaluate(async()=>{const {District}=await import('/studio/district.bundle.mjs');window.picks=[];window.d=new District(document.querySelector('#host'),(group,person)=>{picks.push({group,person});d.selectedGroup=group;});const people=Array.from({length:1500},(_,i)=>({id:'person'+i}));d.update([{name:'Unrecorded',people}],null,null);d.draw();return {calls:d.renderer.info.render.calls,pickables:d.pickables.length,maxHeight:Math.max(...d.pickables.map(o=>o.getWorldPosition(d.camera.position.clone()).y))};});
 assert.ok(stats.calls<100,'static geometry should be batched');assert.ok(stats.maxHeight<10,'1500 people should fit the model');assert.ok(stats.pickables>0);
 const target=await page.evaluate(()=>{const mesh=d.pickables[8],v=mesh.getWorldPosition(d.camera.position.clone()).project(d.camera),r=d.canvas.getBoundingClientRect();return {x:r.x+(v.x+1)*r.width/2,y:r.y+(1-v.y)*r.height/2};});await page.mouse.click(target.x,target.y);await page.mouse.click(target.x,target.y);const picks=await page.evaluate(()=>picks);assert.equal(picks[0].group,'Unrecorded');assert.ok(picks[1].person);
 await page.evaluate(()=>{for(let i=0;i<8;i++)d.update([{name:'Tenant '+i,people:[{id:'new'+i}]}],null,null);d.update([],null,null);});assert.equal(await page.evaluate(()=>d.pickables.length),0);await page.evaluate(()=>d.dispose());
 await page.goto(base+'/studio/?theme=architecture');await page.locator('#district-host canvas').waitFor();await page.locator('[data-theme="editorial"]').last().click();assert.ok(await page.locator('#district-host').isHidden());assert.ok(await page.locator('#tower-index').isHidden());await page.locator('.portrait-card').first().click();await page.getByRole('button',{name:'Add to shortlist'}).waitFor();
 await page.route('**/district.bundle.mjs',r=>r.abort());await page.goto(base+'/studio/?theme=architecture');await page.getByText('The 3D model is unavailable',{exact:false}).waitFor();await page.locator('#tower-index button').first().click();assert.ok(await page.locator('#detail .person-link').count()>0);assert.deepEqual(errors,[]);console.log('PASS: WebGL geometry budget, 1500-person framing, raycast floor selection, rebuild/dispose, theme switching, WebGL-load fallback.');
}finally{await browser.close();}
