const {chromium}=await import(process.env.PLAYWRIGHT_MODULE||'playwright');
import assert from 'node:assert/strict';
const browser=await chromium.launch({headless:true,executablePath:process.env.CHROME_EXECUTABLE||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'});
try{const page=await browser.newPage({viewport:{width:1200,height:900}}),errors=[];page.on('pageerror',e=>errors.push(e.message));const base=process.env.PEOPLE_TEST_ORIGIN||'http://127.0.0.1:4183';await page.route('**/figures-harness',r=>r.fulfill({contentType:'text/html',body:'<div id="host" style="width:950px;height:650px"></div>'}));await page.goto(base+'/figures-harness');await page.evaluate(async()=>{const {District}=await import('/studio/district.bundle.mjs');window.people=Array.from({length:8},(_,i)=>({id:'p'+i,name:'Person '+i}));window.picks=[];window.d=new District(document.querySelector('#host'),(g,p)=>picks.push(p));d.interior('Example',people,0,null);});
const positions=()=>page.evaluate(()=>d.actors.map(a=>a.body.position.toArray()));const first=await positions();await page.waitForTimeout(300);assert.notDeepEqual(await positions(),first);assert.equal(await page.evaluate(()=>d.actors.length),8);assert.equal(await page.evaluate(()=>d.roomMaterials.some(m=>m.map)),false,'no portrait-board textures');
await page.evaluate(()=>d.toggleMotion());const paused=await positions();await page.waitForTimeout(200);assert.deepEqual(await positions(),paused);assert.equal(await page.evaluate(()=>d.frame),null);
const point=await page.evaluate(()=>{const v=d.pickables[4].getWorldPosition(d.camera.position.clone()).project(d.camera),r=d.canvas.getBoundingClientRect();return {x:r.x+(v.x+1)*r.width/2,y:r.y+(1-v.y)*r.height/2};});await page.mouse.click(point.x,point.y);assert.equal(await page.evaluate(()=>picks.at(-1)),'p4');await page.mouse.move(0,0);await page.evaluate(()=>{d.interior('Example',people,0,'p4');d.toggleMotion();});const selected=await page.evaluate(()=>d.actors[4].body.position.toArray());await page.waitForTimeout(200);assert.deepEqual(await page.evaluate(()=>d.actors[4].body.position.toArray()),selected);
await page.emulateMedia({reducedMotion:'reduce'});await page.waitForTimeout(50);assert.equal(await page.evaluate(()=>d.frame),null);const reduced=await positions();await page.waitForTimeout(150);assert.deepEqual(await positions(),reduced);
await page.emulateMedia({reducedMotion:'no-preference'});await page.evaluate(()=>d.update([],null,null));assert.equal(await page.evaluate(()=>d.frame),null);assert.equal(await page.evaluate(()=>d.actors.length),0);await page.evaluate(()=>d.dispose());assert.equal(await page.locator('canvas').count(),0);await page.emulateMedia({reducedMotion:'reduce'});await page.goto(base+'/studio/?theme=architecture');await page.locator('#district-host canvas').waitFor();await page.locator('#tower-index button').first().click();assert.ok(await page.locator('.room-motion').isDisabled());await page.emulateMedia({reducedMotion:'no-preference'});await page.getByRole('button',{name:'Pause movement',exact:true}).waitFor();assert.ok(await page.locator('.room-motion').isEnabled());await page.locator('.room-motion').click();assert.equal(await page.locator('.room-motion').innerText(),'Resume movement');assert.deepEqual(errors,[]);console.log('PASS: moving articulated figures, no boards, pause, raycast identity, selected figure stands still, reduced motion, exterior/dispose cancels animation.');}finally{await browser.close();}
