import assert from 'node:assert/strict';
const {chromium}=await import(process.env.PLAYWRIGHT_MODULE || 'playwright');
const browser=await chromium.launch({executablePath:process.env.CHROME_EXECUTABLE || '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true});
try {
  const page=await browser.newPage({viewport:{width:1280,height:950},reducedMotion:'reduce'});
  page.setDefaultTimeout(10000);
  const errors=[];page.on('pageerror',e=>errors.push(e.message));
  await page.route('**/intelligence-fixture',route=>route.fulfill({contentType:'text/html',body:'<!doctype html><html><head><meta name="viewport" content="width=device-width, initial-scale=1"><link rel="stylesheet" href="/relationship-graph/graph.css"><link rel="stylesheet" href="/relationship-host.css"><link rel="stylesheet" href="/atlas.css"></head><body><div id="graph"></div></body></html>'}));
  await page.goto(`${process.env.PEOPLE_TEST_ORIGIN||'http://127.0.0.1:4194'}/intelligence-fixture`);
  await page.evaluate(async()=>{
    const {mountGraph}=await import('/relationship-graph/graph.mjs');
    const recent=new Date(Date.now()-60000).toISOString();
    window.instance=mountGraph(document.querySelector('#graph'),{graph:{nodes:[
      {id:'a',name:'Ada Rivera',strength:30,directRelationship:true,directLastContact:recent},
      {id:'b',name:'Bo Chen',strength:90,directRelationship:true,directLastContact:'2020-01-01'},
      {id:'c',name:'Shared Person',strength:100,directRelationship:false,directLastContact:null,lastContact:recent,via:['teammate']}
    ],activity:[{id:'email1',kind:'email',at:recent,personIds:['a'],title:'Design review',source:'Gmail metadata'}],edges:[{id:'ab',source:'a',target:'b',kind:'cooccurrence',label:'Shared meeting'}]}});
  });
  const topics=page.getByRole('button',{name:/What’s coming up in your conversations/});
  assert.equal(await topics.getAttribute('aria-expanded'),'false');
  await topics.click();
  assert.match(await page.locator('.rg-topic-bar').innerText(),/No supported conversation topics yet/);
  await topics.click();
  await page.getByRole('button',{name:'Today',exact:true}).click();
  assert.match(await page.locator('.rg-time-summary').innerText(),/^1 person/);
  const timeline=page.getByRole('region',{name:'Activity timeline'});
  assert.equal(await timeline.isVisible(),true);
  assert.match(await timeline.innerText(),/Email message/);
  await timeline.getByRole('button',{name:'Design review',exact:true}).click();
  assert.equal(await page.locator('.rg-node[data-event-active="true"]').count(),1);
  await page.getByRole('button',{name:'Close timeline'}).click();
  assert.equal(await page.locator('.rg-node[data-time-muted="true"]').count(),2);
  await page.getByRole('button',{name:'All time',exact:true}).hover();
  assert.equal(await page.locator('.rg-node[data-time-muted="true"]').count(),0);
  await page.mouse.move(2,2);
  assert.equal(await page.locator('.rg-node[data-time-muted="true"]').count(),2);
  assert.equal(await page.locator('.rg-digest-person').count(),0);
  const digestTab=page.getByRole('button',{name:'Your people',exact:true});
  await digestTab.click();
  assert.equal(await page.getByRole('region',{name:'Daily people digest'}).isVisible(),true);
  await page.getByRole('button',{name:'Close your people'}).click();
  assert.equal(await page.locator('.rg-digest-person').count(),0);
  await digestTab.click();
  await page.getByRole('button',{name:'Recently in touch',exact:true}).click();
  assert.equal(await page.locator('.rg-digest-person').count(),2);
  await page.locator('.rg-digest-person').first().click();
  assert.equal(await page.locator('.rg-profile-score').innerText(),'30 / 100');
  await page.getByRole('button',{name:'Request intro from Bo Chen',exact:true}).click();
  const draft=page.getByRole('dialog',{name:'Introduction request draft'});
  assert.match(await draft.locator('textarea').inputValue(),/Do you know Ada Rivera/);
  await draft.locator('textarea').fill('My edited introduction request');
  await draft.getByRole('button',{name:'Close',exact:true}).click();
  await page.evaluate(()=>window.instance.setSearchAnswer({query:'I need a UI designer',checked:true,results:[{personId:'b',score:.8,reasons:[{summary:'Discussed interface design',observedAt:'2026-09-22'}]}]}));
  assert.equal(await page.locator('.rg-node[data-answer-match="true"]').getAttribute('data-node-id'),'b');
  await page.getByRole('button',{name:'Explore Bo Chen',exact:true}).click();
  assert.match(await page.getByLabel('Selected item and connections').innerText(),/Jev relevance: 80/);
  await page.evaluate(()=>window.instance.setSearchAnswer({query:'unknown',checked:false,results:[]}));
  assert.equal(await page.locator('.rg-node[data-answer-match="true"]').count(),0);
  await page.evaluate(()=>window.instance.setSearchAnswer(null));
  assert.equal(await page.getByRole('button',{name:'Today',exact:true}).getAttribute('aria-pressed'),'true');
  assert.equal(await page.locator('.rg-node[data-time-muted="true"]').count(),2);
  await page.setViewportSize({width:320,height:844});
  await page.locator('.rg-context-panel .rg-close').click();
  await page.getByRole('button',{name:'Your people',exact:true}).click();
  const mobileDigest=await page.getByRole('region',{name:'Daily people digest'}).boundingBox();
  assert.ok(mobileDigest.x>=0 && mobileDigest.y===0 && mobileDigest.width<=320);
  await page.getByRole('button',{name:'Close your people'}).click();
  await page.getByRole('button',{name:'Fit',exact:true}).click();
  await page.getByRole('button',{name:'Explore Shared Person',exact:true}).click();
  assert.equal(await page.locator('.rg-profile-score').innerText(),'Not measured');
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
  await page.screenshot({path:'/tmp/atlas-intelligence-mobile.png',fullPage:true});
  await page.setViewportSize({width:1280,height:950});
  await page.getByRole('button',{name:'Explore Ada Rivera',exact:true}).click();
  await page.screenshot({path:'/tmp/atlas-intelligence-desktop.png',fullPage:true});
  await page.evaluate(()=>{
    const at=new Date().toISOString();
    window.instance.setGraph({nodes:[{id:'a',name:'Ada Rivera'}],edges:[],themes:[{id:'work',canonicalName:'work'}],themeSignals:[{id:'task1',personId:'a',themeId:'work',sourceType:'granola',visibility:'private',observedAt:at,ingestedAt:at,confidence:.9,summary:'Follow up with Ada about the prototype',evidenceRef:'granola-note:test#summary',contentHash:'test',extractorVersion:'test',provenance:{canonicalUrl:'https://notes.granola.ai/d/test',publisherHost:'granola.ai',timeBasis:'observed',observedAt:at,retrievedAt:at,title:'Interface design planning'}}]});
  });
  if(await page.locator('.rg-context-panel .rg-close').count())await page.locator('.rg-context-panel .rg-close').click();
  await page.getByRole('button',{name:'Your people',exact:true}).click();
  await page.getByRole('button',{name:'Needs attention',exact:true}).click();
  assert.match(await page.locator('.rg-attention-card').innerText(),/Possible follow-up/i);
  await page.getByRole('button',{name:'Snooze 7 days',exact:true}).click();
  assert.equal(await page.locator('.rg-attention-card').count(),0);
  await page.getByRole('button',{name:'Reset reviewed suggestions',exact:true}).click();
  await page.getByRole('button',{name:'Mark done',exact:true}).click();
  assert.equal(await page.locator('.rg-attention-card').count(),0);
  await page.evaluate(()=>window.instance.openWander());
  const walk=page.getByRole('region',{name:'Guided graph walk'});
  await walk.getByRole('button',{name:/Interface design planning/}).click();
  assert.match(await walk.innerText(),/Who will you follow/);
  await walk.getByRole('button',{name:/Ada Rivera/}).click();
  assert.match(await walk.innerText(),/Related topics and conversations/);
  await page.evaluate(()=>window.instance.setSearchAnswer({query:'UI help',checked:false,results:[{personId:'a'}]}));
  assert.equal(await walk.count(),0);
  await page.evaluate(()=>window.instance.setSearchAnswer(null));
  assert.match(await walk.innerText(),/Related topics and conversations/);
  await walk.getByRole('button',{name:'← Back',exact:true}).click();
  assert.match(await walk.innerText(),/Interface design planning/);
  await page.evaluate(async()=>{
    window.instance.destroy();
    const {mountGraph}=await import('/relationship-graph/graph.mjs');
    const now=new Date().toISOString();
    const graph={nodes:[{id:'a',name:'Ada',strength:30,combined:40,directRelationship:true}],edges:[],themeSignals:[],activity:[{id:'cal',kind:'calendar',at:new Date(Date.now()+86400000).toISOString(),personIds:['a'],acceptedPersonIds:['a'],status:'accepted',title:'Design review',source:'Google Calendar'}],personFeedback:{}};
    window.instance=mountGraph(document.querySelector('#graph'),{graph,onPersonFeedback:async(id,action)=>{if(action==='clear')delete graph.personFeedback[id];else graph.personFeedback[id]={action,at:Date.now(),until:Date.now()+7*86400000,delta:action==='suppress'?-10:0};return graph;}});
  });
  await page.getByRole('button',{name:'Upcoming',exact:true}).click();
  assert.match(await page.getByRole('region',{name:'Activity timeline'}).innerText(),/Calendar invitation/);
  await page.getByRole('button',{name:'Close timeline'}).click();
  await page.getByRole('button',{name:'Your people',exact:true}).click();
  await page.getByRole('button',{name:'Not interested · −10',exact:true}).click();
  await page.getByText('Reviewed people · Undo',{exact:true}).click();
  await page.getByRole('button',{name:'Ada · Not interested · Undo',exact:true}).waitFor();
  assert.equal(await page.locator('.rg-attention-card').count(),0);
  await page.getByRole('button',{name:'Ada · Not interested · Undo',exact:true}).click();
  await page.getByRole('button',{name:'Not interested · −10',exact:true}).waitFor();
  assert.deepEqual(errors,[]);
  console.log('PASS: time preview and commit, provenance-safe digest, scored profile, editable intro draft, Jev answer lens, empty answers, mobile and reduced motion');
} finally {await browser.close();}
