import {test} from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {MailSync} from '../src/mail-sync';
function fixture(){const db=new DatabaseSync(':memory:'),kv=new Map<string,unknown>();const ctx={storage:{sql:{exec(sql:string,...args:any[]){if(sql.includes('CREATE TABLE')){db.exec(sql);return {toArray:()=>[]};}const stmt=db.prepare(sql);const rows=sql.startsWith('SELECT')?stmt.all(...args):(stmt.run(...args),[]);return {toArray:()=>rows};}},get:async(k:string)=>kv.get(k),put:async(k:string,v:unknown)=>{kv.set(k,v);},delete:async(k:string)=>kv.delete(k),setAlarm:async(n:number)=>{kv.set('alarm',n);},transactionSync(fn:()=>void){db.exec('BEGIN');try{fn();db.exec('COMMIT');}catch(e){db.exec('ROLLBACK');throw e;}}}};const env={MAIL_TOKEN_KEY:'encrypt-key',GOOGLE_CLIENT_SECRET:'client-secret',GOOGLE_CLIENT_ID:'client-id',TOKEN_SECRET:'identity-key'};return {service:new MailSync(ctx as any,env as any),db,kv};}
const originalFetch=globalThis.fetch;
const msg=(id:string)=>({id,internalDate:String(Date.now()-100000),payload:{headers:[{name:'From',value:'Me <me@example.com>'},{name:'To',value:'Ada <ada@example.com>, Bo <bo@example.com>'},{name:'Subject',value:'Design review'},{name:'Message-ID',value:'<same-message>'}]}});
function network(){globalThis.fetch=async(input:any)=>{const url=String(input);if(url.includes('oauth2.googleapis'))return Response.json({access_token:'access'});if(url.includes('/messages?'))return Response.json({messages:[{id:'m1'}]});return Response.json(msg('m1'));};}
test('background import scores automatically, is idempotent, and disconnect removes contributions',async()=>{const {service,db,kv}=fixture();network();try{await service.begin('n',{owner:'owner',verifier:'v',cookie:'c',range:'all',expires:Date.now()+10000,redirect:'x'});await service.attachAccount('me@example.com','refresh','all');assert.ok(!db.prepare('SELECT data FROM accounts').get().data.includes('refresh'));await service.alarm();assert.equal(service.list()[0].status,'connected');const g=await service.graph() as any;assert.equal(g.nodes.length,2);assert.equal(g.edges.length,1);assert.equal(g.edges[0].types[0],'shared_email');assert.ok(g.nodes.every((n:any)=>!n.id.includes('@')));assert.ok(Number(kv.get('alarm'))>Date.now());await service.start('me@example.com');await service.alarm();assert.equal(db.prepare('SELECT COUNT(*) AS n FROM messages').get().n,1);await service.remove('me@example.com');assert.equal(await service.graph(),null);}finally{globalThis.fetch=originalFetch;db.close();}});
test('OAuth connect state is browser-bound, expiring and single use',async()=>{const {service,db}=fixture();await service.begin('n',{owner:'owner',verifier:'v',cookie:'correct',range:'recent',expires:Date.now()+10000,redirect:'x'});assert.equal(await service.consume('n','wrong'),null);assert.ok(await service.consume('n','correct'));assert.equal(await service.consume('n','correct'),null);db.close();});
test('revoked grants stop retries and request reconnection',async()=>{const {service,db}=fixture();try{await service.attachAccount('me@example.com','refresh','all');globalThis.fetch=async()=>Response.json({error:'invalid_grant'},{status:400});await service.alarm();assert.equal(service.list()[0].status,'reconnect');}finally{globalThis.fetch=originalFetch;db.close();}});
test('disconnect during network fetch cannot resurrect imported data',async()=>{const {service,db}=fixture();let release:(r:Response)=>void=()=>{};let entered:()=>void=()=>{};const ready=new Promise<void>(r=>entered=r);try{await service.attachAccount('me@example.com','refresh','all');globalThis.fetch=async(input:any)=>{if(String(input).includes('oauth2.googleapis'))return Response.json({access_token:'access'});if(String(input).includes('/messages?'))return Response.json({messages:[{id:'m1'}]});entered();return new Promise<Response>(r=>release=r);};const running=service.alarm();await ready;await service.remove('me@example.com');release(Response.json(msg('m1')));await running;assert.equal(service.list().length,0);assert.equal(db.prepare('SELECT COUNT(*) AS n FROM contributions').get().n,0);}finally{globalThis.fetch=originalFetch;db.close();}});
test('large imports share batches fairly with other inboxes',async()=>{const {service,db}=fixture();try{await service.attachAccount('me@example.com','first','all');await service.attachAccount('other@example.com','second','all');globalThis.fetch=async(input:any)=>String(input).includes('oauth2.googleapis')?Response.json({access_token:'access'}):String(input).includes('/messages?')?Response.json({messages:Array.from({length:25},(_,i)=>({id:'m'+i}))}):Response.json(msg('m'));await service.alarm();await service.alarm();assert.deepEqual(service.list().map(a=>a.processed),[10,10]);}finally{globalThis.fetch=originalFetch;db.close();}});
test('canonical messages across inboxes count once and survive one disconnect',async()=>{const {service,db}=fixture();network();try{await service.begin('n',{owner:'owner',verifier:'v',cookie:'c',range:'all',expires:Date.now()+10000,redirect:'x'});await service.attachAccount('me@example.com','first','all');await service.attachAccount('other@example.com','second','all');await service.alarm();await service.alarm();assert.equal(db.prepare("SELECT COUNT(DISTINCT canonical) AS n FROM contributions WHERE email='ada@example.com'").get().n,1);await service.remove('other@example.com');assert.equal((await service.graph() as any).nodes.length,2);}finally{globalThis.fetch=originalFetch;db.close();}});
test('Google contact photos attach by email, page fully, and disappear on disconnect',async()=>{const {service,db}=fixture();let calls=0;try{await service.begin('n',{owner:'owner',verifier:'v',cookie:'c',range:'all',expires:Date.now()+10000,redirect:'x'});await service.attachAccount('me@example.com','refresh','all',true);globalThis.fetch=async(input:any)=>{const u=String(input);if(u.includes('oauth2.googleapis'))return Response.json({access_token:'access'});if(u.includes('people.googleapis')){calls++;return Response.json({connections:[{emailAddresses:[{value:calls===1?'ADA@example.com':'bo@example.com'}],photos:[{url:'https://lh3.googleusercontent.com/person',default:false}]}],...(calls===1?{nextPageToken:'page2'}:{})});}if(u.includes('/messages?'))return Response.json({messages:[{id:'m1'}]});return Response.json(msg('m1'));};await service.alarm();assert.equal(service.list()[0].status,'syncing');await service.alarm();assert.equal(service.list()[0].status,'connected');assert.equal((await service.graph() as any).nodes.filter((n:any)=>n.photoUrl).length,2);await service.remove('me@example.com');assert.equal(db.prepare('SELECT COUNT(*) AS n FROM contact_photos').get().n,0);}finally{globalThis.fetch=originalFetch;db.close();}});
test('unavailable Contacts API does not block Gmail sync',async()=>{const {service,db}=fixture();try{await service.attachAccount('me@example.com','refresh','all',true);network();const mail=globalThis.fetch;globalThis.fetch=async(input:any,init:any)=>String(input).includes('people.googleapis')?Response.json({error:{}},{status:403}):mail(input,init);db.prepare('INSERT INTO contact_photos VALUES (?,?,?,?)').run('me@example.com','ada@example.com','https://lh3.googleusercontent.com/old','old');await service.alarm();assert.equal(service.list()[0].status,'connected');assert.equal(service.list()[0].photoStatus,'unavailable');assert.equal(db.prepare('SELECT COUNT(*) AS n FROM contact_photos').get().n,0);}finally{globalThis.fetch=originalFetch;db.close();}});

test('photo completion reports actual available and matching counts, including zero',async()=>{const {service,db}=fixture();try{await service.attachAccount('me@example.com','refresh','all',true);network();const mail=globalThis.fetch;globalThis.fetch=async(input:any,init:any)=>String(input).includes('people.googleapis')?Response.json({connections:[]}):mail(input,init);await service.alarm();assert.equal(service.list()[0].photoCount,0);assert.equal(service.list()[0].matchedPhotoCount,0);db.prepare('INSERT INTO contact_photos VALUES (?,?,?,?)').run('me@example.com','ada@example.com','https://lh3.googleusercontent.com/a','x');db.prepare('INSERT INTO contact_photos VALUES (?,?,?,?)').run('me@example.com','stranger@example.com','https://lh3.googleusercontent.com/b','x');assert.equal(service.list()[0].photoCount,2);assert.equal(service.list()[0].matchedPhotoCount,1);}finally{globalThis.fetch=originalFetch;db.close();}});
