const {chromium}=await import(process.env.PLAYWRIGHT_MODULE || 'playwright');
import assert from 'node:assert/strict';
const browser=await chromium.launch({executablePath:process.env.CHROME_EXECUTABLE || '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true});
const page=await browser.newPage({viewport:{width:1440,height:1060}});
const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.goto('http://127.0.0.1:4182');
await page.waitForTimeout(1300);
assert.equal(await page.locator('.node').count(),50);
await page.screenshot({path:'/tmp/people-lab-atlas.png',fullPage:true});
await page.locator('.node').first().press('Enter');
assert.match(await page.locator('#detail').innerText(),/Connection evidence/i);
await page.getByRole('button',{name:'02 Relationship Pulse'}).click();
assert.match(await page.locator('#view-title').innerText(),/Keep the good/);
await page.screenshot({path:'/tmp/people-lab-pulse.png',fullPage:true});
await page.getByRole('button',{name:'AI agents',exact:true}).click();
assert.equal(await page.getByRole('button',{name:'03 Context Orbits'}).getAttribute('aria-pressed'),'true');
assert.ok(await page.locator('.node').count()<50);
await page.screenshot({path:'/tmp/people-lab-context.png',fullPage:true});
await page.getByRole('textbox').fill('zzzz-no-result');
assert.equal(await page.locator('.node').count(),0);
assert.ok(await page.locator('#empty').isVisible());
await page.getByRole('button',{name:'Reset sample'}).click();
await page.locator('#upload').setInputFiles({name:'example.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify({nodes:[{id:'one',name:'<img src=x onerror=alert(1)>',company:'Example',strength:80}],edges:[]}))});
assert.equal(await page.locator('.node').count(),1);
assert.equal(await page.locator('img').count(),0);
await page.locator('#upload').setInputFiles({name:'bad.json',mimeType:'application/json',buffer:Buffer.from('{}')});
assert.ok((await page.locator('#error').innerText()).length>0);
assert.equal(await page.locator('.node').count(),1);
await page.getByRole('button',{name:'Reset sample'}).click();
await page.setViewportSize({width:390,height:844});
await page.waitForTimeout(400);
assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
await page.screenshot({path:'/tmp/people-lab-mobile.png',fullPage:true});
assert.deepEqual(errors,[]);
console.log('PASS: three views, selection, context filtering, empty results, graph import, invalid import, HTML-safe labels, mobile overflow; no browser errors.');
await browser.close();
