export interface Metadata {id?:string; internalDate?:string; payload?:{headers?:{name:string;value:string}[]}}
export interface GmailPart {mimeType?:string;filename?:string;headers?:{name:string;value:string}[];body?:{data?:string;attachmentId?:string;size?:number};parts?:GmailPart[]}
export interface GmailMessage extends Metadata {payload?:GmailPart}
export interface ParsedMessage {key:string;date:number;subject:string;participants:{email:string;name:string;sent:number;received:number}[]}
const enc=new TextEncoder();
export const b64=(bytes:Uint8Array)=>btoa(String.fromCharCode(...bytes)).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'');
export const bytes=(s:string)=>Uint8Array.from(atob(s.replace(/-/g,'+').replace(/_/g,'/')),c=>c.charCodeAt(0));
export async function digest(s:string){return b64(new Uint8Array(await crypto.subtle.digest('SHA-256',enc.encode(s))));}
export async function opaque(owner:string,value:string,key:string){const k=await crypto.subtle.importKey('raw',enc.encode(key),{name:'HMAC',hash:'SHA-256'},false,['sign']);return b64(new Uint8Array(await crypto.subtle.sign('HMAC',k,enc.encode(owner+'\0'+value))));}
async function encryptionKey(secret:string){return crypto.subtle.importKey('raw',await crypto.subtle.digest('SHA-256',enc.encode(secret)),{name:'AES-GCM'},false,['encrypt','decrypt']);}
export async function seal(value:string,secret:string){const iv=crypto.getRandomValues(new Uint8Array(12));const data=await crypto.subtle.encrypt({name:'AES-GCM',iv},await encryptionKey(secret),enc.encode(value));return b64(iv)+'.'+b64(new Uint8Array(data));}
export async function unseal(value:string,secret:string){const [iv,data]=value.split('.');return new TextDecoder().decode(await crypto.subtle.decrypt({name:'AES-GCM',iv:bytes(iv)},await encryptionKey(secret),bytes(data)));}
function addresses(value:string){const out:{email:string;name:string}[]=[];const parts=value.match(/(?:"[^"\\]*(?:\\.[^"\\]*)*"|[^,])+/g)||[];for(const part of parts){const m=part.match(/([A-Z0-9.!#$%&'*+/=?^_`{|}~-]+@[A-Z0-9.-]+\.[A-Z]{2,})/i);if(!m)continue;const email=m[1].toLowerCase(),name=part.slice(0,m.index).replace(/[<>"]/g,'').trim().slice(0,160);out.push({email,name:name||email.split('@')[0]});}return out;}
export function parseMessage(m:Metadata,account:string):ParsedMessage|null {const date=Number(m.internalDate);if(!m.id||!Number.isFinite(date)||date<=0||date>Date.now()+86400000)return null;const headers=m.payload?.headers||[];const h=(key:string)=>headers.filter(h=>h.name.toLowerCase()===key).map(h=>h.value).join(', ');const from=addresses(h('from')),to=addresses(h('to')+', '+h('cc'));if(!from.length)return null;const sent=from.some(a=>a.email===account);const participants=new Map<string,{email:string;name:string;sent:number;received:number}>();for(const p of [...from,...to]){if(participants.size>=50)break;participants.set(p.email,{...p,sent:sent&&to.some(a=>a.email===p.email)?1:0,received:!sent&&from.some(a=>a.email===p.email)?1:0});}return {key:h('message-id').trim().slice(0,500)||account+':'+m.id,date,subject:h('subject').slice(0,160),participants:[...participants.values()]};}
export function emailScore(sent:number,received:number,days:number){const count=sent+received,reciprocal=Math.min(sent,received)/Math.max(1,Math.max(sent,received));const strength=Math.min(100,Math.round(65*Math.log1p(count)/Math.log(101)+35*reciprocal)),momentum=Math.round(100*Math.exp(-Math.max(0,days)/90));return {strength,momentum,combined:Math.round(strength*.6+momentum*.4),quadrant:strength>=50?(momentum>=50?'nurture':'re-engage'):(momentum>=50?'developing':'deprioritize')};}
