import {DurableObject} from 'cloudflare:workers';
import {parseMessage,emailScore,seal,unseal,opaque, type Metadata} from './mail-model';
export interface MailEnv {MAIL:DurableObjectNamespace<MailSync>;GOOGLE_CLIENT_ID:string;GOOGLE_CLIENT_SECRET?:string;MAIL_TOKEN_KEY?:string;TOKEN_SECRET:string;APP_ORIGIN?:string}
type Range='recent'|'all';
interface Job {photoPage?:string;photosDone?:boolean;generation:string;range:Range;query:string;pageToken?:string;pending:string[];hasMore:boolean;processed:number;started:number;retries:number;lastRun:number;nextAttempt:number}
interface Account {photosEnabled?:boolean;photoStatus?:string;email:string;grant:string;status:string;job:Job|null;lastSync:number;nextSync:number;error:string;range:Range}
interface Pending {verifier:string;cookie:string;expires:number;range:Range;owner:string;redirect:string}
export class MailSync extends DurableObject<MailEnv>{
 constructor(ctx:DurableObjectState,env:MailEnv){super(ctx,env);ctx.storage.sql.exec(`CREATE TABLE IF NOT EXISTS contact_photos (account TEXT NOT NULL,email TEXT NOT NULL,url TEXT NOT NULL,generation TEXT NOT NULL,PRIMARY KEY(account,email)); CREATE TABLE IF NOT EXISTS accounts (email TEXT PRIMARY KEY,data TEXT NOT NULL); CREATE TABLE IF NOT EXISTS messages (account TEXT NOT NULL,id TEXT NOT NULL,canonical TEXT NOT NULL,PRIMARY KEY(account,id)); CREATE TABLE IF NOT EXISTS contributions (account TEXT NOT NULL,canonical TEXT NOT NULL,email TEXT NOT NULL,name TEXT NOT NULL,date INTEGER NOT NULL,subject TEXT NOT NULL,sent INTEGER NOT NULL,received INTEGER NOT NULL,PRIMARY KEY(account,canonical,email)); CREATE INDEX IF NOT EXISTS contributions_email ON contributions(email); CREATE TABLE IF NOT EXISTS mail_edges (account TEXT,canonical TEXT,a TEXT,b TEXT,subject TEXT,PRIMARY KEY(account,canonical,a,b));`);}
 private rows(){return this.ctx.storage.sql.exec<{data:string}>('SELECT data FROM accounts').toArray().map(r=>JSON.parse(r.data) as Account);}
 private get(email:string){const row=this.ctx.storage.sql.exec<{data:string}>('SELECT data FROM accounts WHERE email=?',email).toArray()[0];return row?JSON.parse(row.data) as Account:null;}
 private put(a:Account){this.ctx.storage.sql.exec('INSERT INTO accounts VALUES (?,?) ON CONFLICT(email) DO UPDATE SET data=excluded.data',a.email,JSON.stringify(a));}
 async begin(nonce:string,pending:Pending){await this.ctx.storage.put('pending:'+nonce,pending);await this.ctx.storage.put('owner',pending.owner);}
 async consume(nonce:string,cookie:string){const p=await this.ctx.storage.get<Pending>('pending:'+nonce);if(!p||p.cookie!==cookie||p.expires<Date.now())return null;await this.ctx.storage.delete('pending:'+nonce);return p;}
 async attachAccount(email:string,refresh:string,range:Range,photosEnabled=false){if(!this.env.MAIL_TOKEN_KEY)throw Error('mail_not_configured');if(this.rows().length>=10&&!this.get(email))throw Error('account_limit');const old=this.get(email);const grant=refresh?await seal(refresh,this.env.MAIL_TOKEN_KEY):old?.grant;if(!grant)throw Error('offline_access_missing');const a:Account={email,grant,photosEnabled,photoStatus:photosEnabled?'pending':'permission_required',status:'connected',job:null,lastSync:old?.lastSync||0,nextSync:0,error:'',range};this.put(a);if(!photosEnabled)this.ctx.storage.sql.exec('DELETE FROM contact_photos WHERE account=?',email);await this.start(email,range);}
 list(){return this.rows().map(({email,status,job,lastSync,error,range,photosEnabled,photoStatus})=>({email,status,photosEnabled,photoStatus,processed:job?.processed||0,lastSync,error,range}));}
 async start(email:string,range?:Range){const a=this.get(email);if(!a)throw Error('account_not_found');if(a.job&&a.status==='syncing')return;const selected=range||a.range,initial=!a.lastSync||Boolean(range);const query=initial?(selected==='recent'?'newer_than:90d':''):`after:${Math.floor(a.lastSync/1000)-172800}`;a.job={generation:crypto.randomUUID(),photosDone:!a.photosEnabled,range:selected,query,pageToken:undefined,pending:[],hasMore:true,processed:0,started:Date.now(),retries:0,lastRun:0,nextAttempt:0};a.range=selected;a.status='syncing';a.error='';this.put(a);await this.ctx.storage.setAlarm(Date.now()+1000);}
 async remove(email:string){this.ctx.storage.transactionSync(()=>{this.ctx.storage.sql.exec('DELETE FROM contact_photos WHERE account=?',email);this.ctx.storage.sql.exec('DELETE FROM accounts WHERE email=?',email);this.ctx.storage.sql.exec('DELETE FROM messages WHERE account=?',email);this.ctx.storage.sql.exec('DELETE FROM contributions WHERE account=?',email);this.ctx.storage.sql.exec('DELETE FROM mail_edges WHERE account=?',email);});await this.ctx.storage.delete('graph');}
 private active(a:Account){return this.get(a.email)?.job?.generation===a.job?.generation;}
 private async google(url:string,access:string){const r=await fetch(url,{headers:{authorization:'Bearer '+access},signal:AbortSignal.timeout(20000)});if(!r.ok){const e=new Error(r.status===401?'reconnect_required':r.status===403?'gmail_access_denied':`gmail_${r.status}`);throw e;}return r.json();}
 async alarm(){
  const now=Date.now();for(const a of this.rows()){if(a.status==='connected'&&a.nextSync<=now)await this.start(a.email);}
  const a=this.rows().filter(a=>a.status==='syncing'&&(a.job?.nextAttempt||0)<=now).sort((a,b)=>(a.job?.lastRun||0)-(b.job?.lastRun||0))[0];
  if(a?.job){a.job.lastRun=now;this.put(a);try{await this.batch(a);}catch(e){if(this.active(a)){const current=this.get(a.email)!;current.job!.retries++;current.job!.nextAttempt=Date.now()+Math.min(300000,5000*2**current.job!.retries);const message=e instanceof Error?e.message:'sync_failed';current.error=message;current.status=message==='reconnect_required'?'reconnect':current.job!.retries>=6?'error':'syncing';this.put(current);}}}
  const pending=this.rows().filter(a=>a.status==='syncing');const idle=this.rows().filter(a=>a.status==='connected');if(pending.length)await this.ctx.storage.setAlarm(Math.max(Date.now()+1500,Math.min(...pending.map(a=>a.job?.nextAttempt||0))));else if(idle.length)await this.ctx.storage.setAlarm(Math.max(Date.now()+1000,Math.min(...idle.map(a=>a.nextSync))));
 }
 private async photoBatch(a:Account,access:string){const job=a.job!;if(!a.photosEnabled||job.photosDone)return;try{const url=new URL('https://people.googleapis.com/v1/people/me/connections');url.searchParams.set('personFields','emailAddresses,photos');url.searchParams.set('pageSize','1000');if(job.photoPage)url.searchParams.set('pageToken',job.photoPage);const response=await fetch(url,{headers:{authorization:'Bearer '+access},signal:AbortSignal.timeout(20000)});if(!response.ok){if((response.status===401||response.status===403)&&this.active(a))this.ctx.storage.sql.exec('DELETE FROM contact_photos WHERE account=?',a.email);throw Error('photos_unavailable');}const data=await response.json() as {connections?:{emailAddresses?:{value?:string}[];photos?:{url?:string;default?:boolean}[]}[];nextPageToken?:string};if(!this.active(a))return;this.ctx.storage.transactionSync(()=>{for(const person of data.connections||[]){const photo=person.photos?.find(p=>{try{const u=new URL(p.url||'');return !p.default&&u.protocol==='https:'&&(u.hostname==='googleusercontent.com'||u.hostname.endsWith('.googleusercontent.com'))&&!u.username&&!u.password;}catch{return false;}});if(!photo?.url)continue;for(const address of person.emailAddresses||[]){const email=address.value?.trim().toLowerCase();if(email&&email.length<=320)this.ctx.storage.sql.exec('INSERT OR REPLACE INTO contact_photos VALUES (?,?,?,?)',a.email,email,photo.url,job.generation);}}job.photoPage=data.nextPageToken;job.photosDone=!data.nextPageToken;if(job.photosDone)this.ctx.storage.sql.exec('DELETE FROM contact_photos WHERE account=? AND generation<>?',a.email,job.generation);a.photoStatus=job.photosDone?'ready':'syncing';this.put(a);});}catch{if(!this.active(a))return;job.photosDone=true;a.photoStatus='unavailable';this.put(a);}}
 private async batch(a:Account){const job=a.job!;if(!this.env.MAIL_TOKEN_KEY||!this.env.GOOGLE_CLIENT_SECRET)throw Error('mail_not_configured');const refresh=await unseal(a.grant,this.env.MAIL_TOKEN_KEY);const tr=await fetch('https://oauth2.googleapis.com/token',{method:'POST',body:new URLSearchParams({client_id:this.env.GOOGLE_CLIENT_ID,client_secret:this.env.GOOGLE_CLIENT_SECRET,refresh_token:refresh,grant_type:'refresh_token'}),signal:AbortSignal.timeout(20000)});if(!tr.ok){const err=await tr.json() as {error?:string};throw Error(err.error==='invalid_grant'?'reconnect_required':`token_${tr.status}`);}const tokens=await tr.json() as {access_token:string};if(!this.active(a))return;
  await this.photoBatch(a,tokens.access_token);if(!this.active(a))return;
  if(!job.pending.length&&job.hasMore){const url=new URL('https://gmail.googleapis.com/gmail/v1/users/me/messages');url.searchParams.set('maxResults','25');url.searchParams.set('q',job.query);if(job.pageToken)url.searchParams.set('pageToken',job.pageToken);const listing=await this.google(url.href,tokens.access_token) as {messages?:{id:string}[];nextPageToken?:string};if(!this.active(a))return;job.pending=(listing.messages||[]).map(m=>m.id);job.pageToken=listing.nextPageToken;job.hasMore=Boolean(listing.nextPageToken);this.put(a);}
  const ids=job.pending.slice(0,10);for(const id of ids){const seen=this.ctx.storage.sql.exec('SELECT id FROM messages WHERE account=? AND id=?',a.email,id).toArray().length;if(!seen){const url=new URL('https://gmail.googleapis.com/gmail/v1/users/me/messages/'+encodeURIComponent(id));url.searchParams.set('format','metadata');for(const header of ['From','To','Cc','Date','Subject','Message-ID'])url.searchParams.append('metadataHeaders',header);let raw:Metadata;try{raw=await this.google(url.href,tokens.access_token) as Metadata;}catch(e){if(e instanceof Error&&e.message==='gmail_404'){job.pending.shift();job.processed++;if(this.active(a))this.put(a);continue;}throw e;}if(!this.active(a))return;const parsed=parseMessage(raw,a.email);this.ctx.storage.transactionSync(()=>{if(parsed){for(const p of parsed.participants){if(p.email===a.email||/^(no-?reply|notifications?|newsletters?|mailer-daemon)@/i.test(p.email)||(!p.sent&&!p.received))continue;this.ctx.storage.sql.exec('INSERT OR REPLACE INTO contributions VALUES (?,?,?,?,?,?,?,?)',a.email,parsed.key,p.email,p.name,parsed.date,parsed.subject,p.sent,p.received);}const contacts=parsed.participants.filter(p=>p.email!==a.email&&(p.sent||p.received)).slice(0,8).sort((x,y)=>x.email.localeCompare(y.email));for(let i=0;i<contacts.length;i++)for(let j=i+1;j<contacts.length;j++)this.ctx.storage.sql.exec('INSERT OR IGNORE INTO mail_edges VALUES (?,?,?,?,?)',a.email,parsed.key,contacts[i].email,contacts[j].email,parsed.subject);this.ctx.storage.sql.exec('INSERT OR IGNORE INTO messages VALUES (?,?,?)',a.email,id,parsed?.key||id);}else this.ctx.storage.sql.exec('INSERT OR IGNORE INTO messages VALUES (?,?,?)',a.email,id,id);});}
   if(!this.active(a))return;job.pending.shift();job.processed++;job.retries=0;job.nextAttempt=0;a.error='';this.put(a);
  }
  await this.ctx.storage.delete('graph');
  if(!job.pending.length&&!job.hasMore&&(!a.photosEnabled||job.photosDone)){a.status='connected';a.lastSync=job.started;a.nextSync=Date.now()+3600000;this.put(a);}
 }
 async graph(){const owner=await this.ctx.storage.get<string>('owner');if(!owner)return null;const accounts=this.rows();if(!accounts.length)return null;const own=new Set(accounts.map(a=>a.email));
  const rows=this.ctx.storage.sql.exec<{email:string;name:string;sent:number;received:number;last:number}>(`SELECT email, MAX(name) AS name, SUM(sent) AS sent, SUM(received) AS received, MAX(date) AS last FROM (SELECT canonical,email,MAX(name) AS name,MAX(sent) AS sent,MAX(received) AS received,MAX(date) AS date FROM contributions GROUP BY canonical,email) GROUP BY email ORDER BY SUM(sent)+SUM(received) DESC LIMIT 1510`).toArray().filter(r=>!own.has(r.email)).slice(0,1500);
  const photos=new Map(this.ctx.storage.sql.exec<{email:string;url:string}>('SELECT email,MAX(url) AS url FROM contact_photos GROUP BY email').toArray().map(p=>[p.email,p.url]));
  const nodes=await Promise.all(rows.map(async r=>({id:await opaque(owner,r.email,this.env.TOKEN_SECRET),photoUrl:photos.get(r.email)||null,name:r.name.includes('@')?r.email.split('@')[0]:r.name,company:r.email.split('@')[1],companySource:'email_domain',lastContact:new Date(r.last).toISOString(),...emailScore(r.sent,r.received,(Date.now()-r.last)/86400000)})));
  const idMap=new Map(rows.map((r,i)=>[r.email,nodes[i].id]));const edges=this.ctx.storage.sql.exec<{a:string;b:string;weight:number;subject:string}>('SELECT a,b,COUNT(DISTINCT canonical) AS weight,MAX(subject) AS subject FROM mail_edges GROUP BY a,b ORDER BY weight DESC LIMIT 5000').toArray().filter(e=>idMap.has(e.a)&&idMap.has(e.b)).map(e=>({source:idMap.get(e.a),target:idMap.get(e.b),weight:e.weight,types:['shared_email'],contexts:[e.subject]}));
  const value={pushedAt:new Date(Math.max(...accounts.map(a=>Math.max(a.lastSync,a.job?.lastRun||0)))).toISOString(),nodes,edges,source:'email_accounts',scoreModel:'email-frequency-reciprocity-recency-v1',note:'Company labels are email domains. Message metadata only; no message bodies. Mailbox deletions are not reconciled automatically.'};
  // Never cache after an await: a disconnect or another batch may have changed the data.
  return value;
 }
}
