/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 846a3abd8335fec5f8f270b7833a2189)
interface __BaseEnv_Env {
	DB: D1Database;
	AI: Ai;
	ASSETS: Fetcher;
	APP_ORIGIN: "https://people-graph.kayarjones901.workers.dev";
	GOOGLE_CLIENT_ID: "726397126192-d5esd42caksfb95hcoh12vpuji8kv008.apps.googleusercontent.com";
	THEME_MODEL: "@cf/meta/llama-3.3-70b-instruct-fp8-fast";
	MAIL: DurableObjectNamespace<import("./src/index").MailSync>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "MailSync";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
